# Generated by Django 4.2.7 on 2023-11-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='trust_descriptions',
            field=models.TextField(default=1, verbose_name='Описание доверие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='trust_descriptions2',
            field=models.TextField(default=1, verbose_name='Описание доверие №2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='trust_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок доверие'),
            preserve_default=False,
        ),
    ]
