# Generated by Django 4.2.7 on 2023-11-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_trust_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='trust_image',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='фото'),
            preserve_default=False,
        ),
    ]
