# Generated by Django 4.2.7 on 2023-11-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_delivery_trust_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='descriptions_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание доставки'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='descriptions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание доставки'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок доставки'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок доставки'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='trust_descriptions2_ky',
            field=models.TextField(null=True, verbose_name='Описание доверие №2'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='trust_descriptions2_ru',
            field=models.TextField(null=True, verbose_name='Описание доверие №2'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='trust_descriptions_ky',
            field=models.TextField(null=True, verbose_name='Описание доверие'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='trust_descriptions_ru',
            field=models.TextField(null=True, verbose_name='Описание доверие'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='trust_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок доверие'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='trust_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок доверие'),
        ),
    ]
