# Generated by Django 4.2.7 on 2023-11-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTaxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок партнерство')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Этапы партнерство',
                'verbose_name_plural': 'Этапы партнерство',
            },
        ),
        migrations.CreateModel(
            name='Partnsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок партнерство')),
                ('title2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок партнерство')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание партнерство')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото баннера')),
                ('become_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок СТАТЬ ПАРТНЕРОМ ')),
                ('become_descriptions', models.TextField(blank=True, null=True, verbose_name='Описание СТАТЬ ПАРТНЕРОМ ')),
                ('become_image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото СТАТЬ ПАРТНЕРОМ ')),
                ('local_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Локальный таксопарк')),
                ('local_title2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Локальный таксопарк')),
                ('local_descriptions', models.TextField(blank=True, null=True, verbose_name='Описание Локальный таксопарк')),
                ('getting_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Что вы получаете')),
                ('getting_descriptions', models.TextField(blank=True, null=True, verbose_name='Описание Что вы получаете')),
                ('getting_descriptions2', models.TextField(blank=True, null=True, verbose_name='Описание Что вы получаете')),
                ('getting_descriptions3', models.TextField(blank=True, null=True, verbose_name='Описание Что вы получаете')),
            ],
            options={
                'verbose_name': 'Найстрока страницы партнерство',
                'verbose_name_plural': 'Найстрока страницы партнерство',
            },
        ),
    ]
