# Generated by Django 4.2.7 on 2023-11-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partnsers',
            new_name='Patners',
        ),
    ]
