# Generated by Django 4.2.7 on 2023-11-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_rename_partnsers_patners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patners',
            new_name='Partners',
        ),
    ]
