# Generated by Django 4.2.7 on 2023-11-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_mission', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок о нас ')),
                ('mission_descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание о нас')),
                ('vision', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок о нас №2')),
                ('vision_descriptions', models.CharField(max_length=255, verbose_name='Описание о нас')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото баннера')),
            ],
            options={
                'verbose_name': 'Настройка страницы о нас',
                'verbose_name_plural': 'Настройки страницы о нас',
            },
        ),
    ]
