# Generated by Django 4.2.7 on 2023-11-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='vision_descriptions',
            field=models.CharField(max_length=255, verbose_name='Описание о нас №2'),
        ),
    ]
