# Generated by Django 4.2.7 on 2023-11-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_vision_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('descriptions', models.TextField(verbose_name='Описание ')),
                ('descriptions2', models.TextField(verbose_name='Описание №2')),
                ('numbers', models.CharField(max_length=10, verbose_name='Номерация')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Наша миссия',
                'verbose_name_plural': 'Наша миссия',
            },
        ),
    ]
