# Generated by Django 4.2.7 on 2023-11-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_ourmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourmission',
            name='descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='Описание '),
        ),
        migrations.AlterField(
            model_name='ourmission',
            name='descriptions2',
            field=models.TextField(blank=True, null=True, verbose_name='Описание №2'),
        ),
        migrations.AlterField(
            model_name='ourmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ourmission',
            name='numbers',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номерация'),
        ),
        migrations.AlterField(
            model_name='ourmission',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
