# Generated by Django 4.2.7 on 2023-11-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_rename_mission_descriptions_kg_about_mission_descriptions_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourmission',
            name='numbers_ky',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номерация'),
        ),
        migrations.AddField(
            model_name='ourmission',
            name='numbers_ru',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номерация'),
        ),
    ]
