# Generated by Django 4.2.7 on 2023-11-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание контакты')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото баннера')),
            ],
            options={
                'verbose_name': 'Найстрока страницы контакты',
                'verbose_name_plural': 'Найстрока страницы контакты',
            },
        ),
    ]
