# Generated by Django 4.2.7 on 2023-11-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_banner_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='descriptions_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание контакты'),
        ),
        migrations.AddField(
            model_name='contact',
            name='descriptions_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание контакты'),
        ),
    ]
