# Generated by Django 4.2.7 on 2023-11-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_descriptions_ky_contact_descriptions_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваше ФИО '),
        ),
        migrations.AddField(
            model_name='contact',
            name='firstname_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваше ФИО '),
        ),
        migrations.AddField(
            model_name='contact',
            name='firstname_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваше ФИО '),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании '),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_company_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании '),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_company_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании '),
        ),
        migrations.AddField(
            model_name='contact',
            name='number_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='номер телефона/e-mail '),
        ),
        migrations.AddField(
            model_name='contact',
            name='number_email_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='номер телефона/e-mail '),
        ),
        migrations.AddField(
            model_name='contact',
            name='number_email_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='номер телефона/e-mail '),
        ),
    ]
