# Generated by Django 4.2.7 on 2023-11-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_firstname_contact_firstname_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title_form',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' Заголовок формы'),
        ),
    ]
