# Generated by Django 4.2.7 on 2023-11-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта')),
                ('descriptions', models.TextField(verbose_name='Описание сайта')),
                ('banner_image', models.ImageField(upload_to='image/', verbose_name='Фото баннера')),
                ('logo', models.ImageField(upload_to='image/', verbose_name='Лого фото')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
