# Generated by Django 4.2.7 on 2023-11-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта №2'),
        ),
        migrations.AlterField(
            model_name='index',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото баннера'),
        ),
        migrations.AlterField(
            model_name='index',
            name='descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сайта'),
        ),
        migrations.AlterField(
            model_name='index',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Лого фото'),
        ),
        migrations.AlterField(
            model_name='index',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта №1'),
        ),
    ]
