# Generated by Django 4.2.7 on 2023-11-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_index_banner_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='image_slider',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Фото слайдера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='numbering',
            field=models.CharField(default=1, max_length=255, verbose_name='Номерация слайдера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='title_slider',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок слайдера'),
        ),
        migrations.AlterField(
            model_name='index',
            name='descriptions',
            field=models.TextField(default=1, verbose_name='Описание слайлера'),
            preserve_default=False,
        ),
    ]
