# Generated by Django 4.2.7 on 2023-11-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_index_image_slider_index_numbering_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='Settings',
        ),
    ]
