# Generated by Django 4.2.7 on 2023-11-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_index_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_slider', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок слайдера')),
                ('numbering', models.CharField(max_length=255, verbose_name='Номерация слайдера')),
                ('descriptions', models.TextField(verbose_name='Описание слайлера')),
                ('image_slider', models.ImageField(upload_to='image/', verbose_name='Фото слайдера')),
            ],
            options={
                'verbose_name': 'Настройка слайдера',
                'verbose_name_plural': 'Настройки слайдера',
            },
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_slider',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='numbering',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='title_slider',
        ),
        migrations.AlterField(
            model_name='settings',
            name='descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сайта'),
        ),
    ]
