# Generated by Django 4.2.7 on 2023-11-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_why_alter_slider_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='why',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Иконка'),
        ),
    ]
