# Generated by Django 4.2.7 on 2023-11-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_why_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='why',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка'),
        ),
    ]
