# Generated by Django 4.2.7 on 2023-11-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_why_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='why',
            name='why',
            field=models.CharField(default=1, max_length=255, verbose_name='Вопрос'),
            preserve_default=False,
        ),
    ]
