# Generated by Django 4.2.7 on 2023-11-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_why_why'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='advantage1',
            field=models.CharField(default=1, max_length=255, verbose_name='Преимущества №1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='advantage2',
            field=models.CharField(default=1, max_length=255, verbose_name='преимущества №2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='advantage3',
            field=models.CharField(default=1, max_length=255, verbose_name='преимущества №3'),
            preserve_default=False,
        ),
    ]
