# Generated by Django 4.2.7 on 2023-11-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_settings_advantage1_settings_advantage2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='advantage1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Преимущества №1'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='advantage2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='преимущества №2'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='advantage3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='преимущества №3'),
        ),
    ]
