# Generated by Django 4.2.7 on 2023-11-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_settings_advantage1_alter_settings_advantage2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='made_descriptions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание где сделано'),
        ),
        migrations.AddField(
            model_name='settings',
            name='made_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Где сделано?'),
        ),
    ]
