# Generated by Django 4.2.7 on 2023-11-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_settings_install'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройка страницы главная', 'verbose_name_plural': 'Настройки главная'},
        ),
    ]
