# Generated by Django 4.2.7 on 2023-11-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_settings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderСity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('numbers', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номерация')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото')),
            ],
        ),
    ]
