# Generated by Django 4.2.7 on 2023-11-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_orderсity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderсity',
            options={'verbose_name': 'Как заказать такси внутри города?', 'verbose_name_plural': 'Как заказать такси внутри города?'},
        ),
        migrations.AddField(
            model_name='orderсity',
            name='title_order',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Как заказать такси внутри города?'),
        ),
    ]
