# Generated by Django 4.2.7 on 2023-11-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_why_title_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIntercity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('numbers', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номерация')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Как заказать такси межгород?',
                'verbose_name_plural': 'Как заказать такси внутри межгород?',
            },
        ),
    ]
