# Generated by Django 4.2.7 on 2023-11-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_orderintercity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='image/')),
            ],
            options={
                'verbose_name': 'С ALAGET зарабатывать легко!',
                'verbose_name_plural': 'С ALAGET зарабатывать легко!',
            },
        ),
    ]
