# Generated by Django 4.2.7 on 2023-11-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_earn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earn',
            name='descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='earn',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='earn',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
