# Generated by Django 4.2.7 on 2023-11-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_earn_descriptions_alter_earn_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earn',
            name='descriptions_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='earn',
            name='descriptions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='earn',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='earn',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='orderintercity',
            name='descriptions_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='orderintercity',
            name='descriptions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='orderintercity',
            name='numbers_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номерация'),
        ),
        migrations.AddField(
            model_name='orderintercity',
            name='numbers_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номерация'),
        ),
        migrations.AddField(
            model_name='orderintercity',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='orderintercity',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='orderсity',
            name='descriptions_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='orderсity',
            name='descriptions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='orderсity',
            name='numbers_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номерация'),
        ),
        migrations.AddField(
            model_name='orderсity',
            name='numbers_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номерация'),
        ),
        migrations.AddField(
            model_name='orderсity',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='orderсity',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='settings',
            name='advantage1_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Преимущества №1'),
        ),
        migrations.AddField(
            model_name='settings',
            name='advantage1_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Преимущества №1'),
        ),
        migrations.AddField(
            model_name='settings',
            name='advantage2_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='преимущества №2'),
        ),
        migrations.AddField(
            model_name='settings',
            name='advantage2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='преимущества №2'),
        ),
        migrations.AddField(
            model_name='settings',
            name='advantage3_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='преимущества №3'),
        ),
        migrations.AddField(
            model_name='settings',
            name='advantage3_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='преимущества №3'),
        ),
        migrations.AddField(
            model_name='settings',
            name='descriptions_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сайта'),
        ),
        migrations.AddField(
            model_name='settings',
            name='descriptions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сайта'),
        ),
        migrations.AddField(
            model_name='settings',
            name='install_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Установить приложение'),
        ),
        migrations.AddField(
            model_name='settings',
            name='install_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Установить приложение'),
        ),
        migrations.AddField(
            model_name='settings',
            name='made_descriptions_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание где сделано'),
        ),
        migrations.AddField(
            model_name='settings',
            name='made_descriptions_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание где сделано'),
        ),
        migrations.AddField(
            model_name='settings',
            name='made_title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Где сделано?'),
        ),
        migrations.AddField(
            model_name='settings',
            name='made_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Где сделано?'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title2_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта №2'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта №2'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта №1'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта №1'),
        ),
        migrations.AddField(
            model_name='slider',
            name='descriptions_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание слайлера'),
        ),
        migrations.AddField(
            model_name='slider',
            name='descriptions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание слайлера'),
        ),
        migrations.AddField(
            model_name='slider',
            name='numbering_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номерация слайдера'),
        ),
        migrations.AddField(
            model_name='slider',
            name='numbering_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номерация слайдера'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_slider_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок слайдера'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_slider_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок слайдера'),
        ),
        migrations.AddField(
            model_name='why',
            name='descriptions_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='why',
            name='descriptions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='why',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='why',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='why',
            name='why_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='why',
            name='why_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
    ]
