# Generated by Django 4.2.7 on 2023-11-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_earn_descriptions_ky_earn_descriptions_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='title_slider2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок слайдера 2'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_slider2_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок слайдера 2'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_slider2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок слайдера 2'),
        ),
    ]
