# Generated by Django 4.2.7 on 2023-11-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_slider_title_slider2_slider_title_slider2_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=255, null=True, verbose_name='ГЛАВНАЯ')),
                ('title1_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='ГЛАВНАЯ')),
                ('title1_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='ГЛАВНАЯ')),
                ('title2', models.CharField(blank=True, max_length=255, null=True, verbose_name='ТАКСИ')),
                ('title2_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='ТАКСИ')),
                ('title2_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='ТАКСИ')),
                ('title3', models.CharField(blank=True, max_length=255, null=True, verbose_name='ГРУЗОПЕРЕВОЗКИ')),
                ('title3_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='ГРУЗОПЕРЕВОЗКИ')),
                ('title3_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='ГРУЗОПЕРЕВОЗКИ')),
                ('title4', models.CharField(blank=True, max_length=255, null=True, verbose_name='ДОСТАВКА')),
                ('title4_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='ДОСТАВКА')),
                ('title4_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='ДОСТАВКА')),
                ('title5', models.CharField(blank=True, max_length=255, null=True, verbose_name='О НАС')),
                ('title5_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='О НАС')),
                ('title5_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='О НАС')),
                ('title6', models.CharField(blank=True, max_length=255, null=True, verbose_name='КОНТАКТЫ')),
                ('title6_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='КОНТАКТЫ')),
                ('title6_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='КОНТАКТЫ')),
                ('title7', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стать водителем')),
                ('title7_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стать водителем')),
                ('title7_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стать водителем')),
                ('title8', models.CharField(blank=True, max_length=255, null=True, verbose_name='РАБОТА В АЛАГЕТ')),
                ('title8_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='РАБОТА В АЛАГЕТ')),
                ('title8_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='РАБОТА В АЛАГЕТ')),
                ('title9', models.CharField(blank=True, max_length=255, null=True, verbose_name='ПАРТНЕРСТВО')),
                ('title9_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='ПАРТНЕРСТВО')),
                ('title9_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='ПАРТНЕРСТВО')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Footer text')),
                ('descriptions_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Footer text')),
                ('descriptions_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Footer text')),
            ],
            options={
                'verbose_name': 'Страницы',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
