# Generated by Django 4.2.7 on 2023-11-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='descriptions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='descriptions2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='descriptions2_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='descriptions2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='descriptions3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='descriptions3_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='descriptions3_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='descriptions_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='descriptions_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
    ]
