# Generated by Django 4.2.7 on 2023-11-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Betaxist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок стать водителем')),
                ('title2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок стать водителем №2')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание стать водителем')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото баннера')),
                ('join_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок присоединиться')),
                ('join_descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок присоединиться')),
                ('join_image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото присоединиться')),
            ],
            options={
                'verbose_name': 'Найстрока страницы стать водителем',
                'verbose_name_plural': 'Найстрока страницы стать водителем',
            },
        ),
    ]
