# Generated by Django 4.2.7 on 2023-11-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betaxist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betaxist',
            name='descriptions',
        ),
    ]
