# Generated by Django 4.2.7 on 2023-11-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betaxist', '0003_alter_betaxist_join_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarnMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'КАК ЖЕ НАЧАТЬ ЗАРАБАТЫВАТЬ С ALAGET?',
                'verbose_name_plural': 'КАК ЖЕ НАЧАТЬ ЗАРАБАТЫВАТЬ С ALAGET?',
            },
        ),
    ]
