# Generated by Django 4.2.7 on 2023-11-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betaxist', '0004_earnmoney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earnmoney',
            name='image',
        ),
        migrations.AddField(
            model_name='earnmoney',
            name='numbers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номерация'),
        ),
    ]
