# Generated by Django 4.2.7 on 2023-11-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betaxist', '0005_remove_earnmoney_image_earnmoney_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='betaxist',
            name='join_descriptions_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание присоединиться'),
        ),
        migrations.AddField(
            model_name='betaxist',
            name='join_descriptions_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание присоединиться'),
        ),
        migrations.AddField(
            model_name='betaxist',
            name='join_title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок присоединиться'),
        ),
        migrations.AddField(
            model_name='betaxist',
            name='join_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок присоединиться'),
        ),
        migrations.AddField(
            model_name='betaxist',
            name='title2_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок стать водителем №2'),
        ),
        migrations.AddField(
            model_name='betaxist',
            name='title2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок стать водителем №2'),
        ),
        migrations.AddField(
            model_name='betaxist',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок стать водителем'),
        ),
        migrations.AddField(
            model_name='betaxist',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок стать водителем'),
        ),
        migrations.AddField(
            model_name='earnmoney',
            name='descriptions_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='earnmoney',
            name='descriptions_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='earnmoney',
            name='numbers_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номерация'),
        ),
        migrations.AddField(
            model_name='earnmoney',
            name='numbers_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номерация'),
        ),
        migrations.AddField(
            model_name='earnmoney',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='earnmoney',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
