# Generated by Django 4.2.7 on 2023-11-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок грузоперевозки')),
                ('title2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок грузоперевозки №2')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание грузоперевозки')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото баннера')),
            ],
            options={
                'verbose_name': 'Найстрока страницы грузоперевозки',
                'verbose_name_plural': 'Найстрока страницы грузоперевозки',
            },
        ),
    ]
