# Generated by Django 4.2.7 on 2023-11-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_remove_cargo_title2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profitable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото ')),
            ],
            options={
                'verbose_name': 'Приложение для выгодных грузоперевозок',
                'verbose_name_plural': 'Приложение для выгодных грузоперевозок',
            },
        ),
    ]
