# Generated by Django 4.2.7 on 2023-11-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_profitable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='descriptions_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание грузоперевозки'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='descriptions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание грузоперевозки'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок грузоперевозки'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок грузоперевозки'),
        ),
        migrations.AddField(
            model_name='profitable',
            name='descriptions_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание '),
        ),
        migrations.AddField(
            model_name='profitable',
            name='descriptions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание '),
        ),
        migrations.AddField(
            model_name='profitable',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='profitable',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
