# Generated by Django 4.2.7 on 2023-11-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_typestaxi_alter_taxi_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='typestaxi',
            name='descriptions2',
            field=models.TextField(blank=True, null=True, verbose_name='Описание типов такси'),
        ),
        migrations.AddField(
            model_name='typestaxi',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='typestaxi',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок типов такси'),
        ),
    ]
