# Generated by Django 4.2.7 on 2023-11-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_typestaxi_descriptions2_typestaxi_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typestaxi',
            name='descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='Описание типов такси №1'),
        ),
        migrations.AlterField(
            model_name='typestaxi',
            name='descriptions2',
            field=models.TextField(blank=True, null=True, verbose_name='Описание типов такси№2'),
        ),
        migrations.AlterField(
            model_name='typestaxi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото типов такси  №1'),
        ),
        migrations.AlterField(
            model_name='typestaxi',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото типов такси №2'),
        ),
        migrations.AlterField(
            model_name='typestaxi',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок типов такси №1'),
        ),
        migrations.AlterField(
            model_name='typestaxi',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок типов такси  №2'),
        ),
    ]
