# Generated by Django 4.2.7 on 2023-11-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_alter_typestaxi_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typestaxi',
            name='slide_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок слайдера'),
            preserve_default=False,
        ),
    ]
