# Generated by Django 4.2.7 on 2023-11-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_typestaxi_slide_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typestaxi',
            name='slide_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок слайдера'),
        ),
    ]
