# Generated by Django 4.2.7 on 2023-11-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0006_alter_typestaxi_slide_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='typestaxi',
            name='title_order',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Как заказать такси внутри города?'),
        ),
    ]
