# Generated by Django 4.2.7 on 2023-11-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_typestaxi_title_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typestaxi',
            name='title_order',
        ),
        migrations.AddField(
            model_name='taxi',
            name='title_order',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Как заказать такси внутри города?'),
        ),
    ]
