# Generated by Django 4.2.7 on 2023-11-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0008_remove_typestaxi_title_order_taxi_title_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='title_order2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Как заказать такси внутри города?'),
        ),
    ]
