# Generated by Django 4.2.7 on 2023-11-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0009_taxi_title_order2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='title_order',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Как заказать такси внутри города?'),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='title_order2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Как заказать такси межгород?'),
        ),
    ]
