# Generated by Django 4.2.7 on 2023-11-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0010_alter_taxi_title_order_alter_taxi_title_order2'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='advantage1_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Преимущества №1'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='advantage1_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Преимущества №1'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='advantage2_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='преимущества №2'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='advantage2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='преимущества №2'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='advantage3_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='преимущества №3'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='advantage3_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='преимущества №3'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='descriptions_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сайта'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='descriptions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сайта'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='title2_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта №2'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='title2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта №2'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта №1'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='title_order2_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Как заказать такси межгород?'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='title_order2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Как заказать такси межгород?'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='title_order_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Как заказать такси внутри города?'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='title_order_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Как заказать такси внутри города?'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта №1'),
        ),
        migrations.AddField(
            model_name='typestaxi',
            name='descriptions2_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание типов такси№2'),
        ),
        migrations.AddField(
            model_name='typestaxi',
            name='descriptions2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание типов такси№2'),
        ),
        migrations.AddField(
            model_name='typestaxi',
            name='descriptions_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание типов такси №1'),
        ),
        migrations.AddField(
            model_name='typestaxi',
            name='descriptions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание типов такси №1'),
        ),
        migrations.AddField(
            model_name='typestaxi',
            name='slide_title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок слайдера'),
        ),
        migrations.AddField(
            model_name='typestaxi',
            name='slide_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок слайдера'),
        ),
        migrations.AddField(
            model_name='typestaxi',
            name='title2_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок типов такси  №2'),
        ),
        migrations.AddField(
            model_name='typestaxi',
            name='title2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок типов такси  №2'),
        ),
        migrations.AddField(
            model_name='typestaxi',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок типов такси №1'),
        ),
        migrations.AddField(
            model_name='typestaxi',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок типов такси №1'),
        ),
    ]
